<a href="https://colab.research.google.com/github/VictorYuzoBR/learning-phyton/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local/miniconda
!rm Miniconda3-latest-Linux-x86_64.sh

--2024-09-08 13:26:43--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.32.241, 104.16.191.158, 2606:4700::6810:20f1, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.32.241|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 148981743 (142M) [application/octet-stream]
Saving to: ‘Miniconda3-latest-Linux-x86_64.sh’

Miniconda3-latest-L 100%[===================>] 142.08M   147MB/s    in 1.0s    

2024-09-08 13:26:44 (147 MB/s) - ‘Miniconda3-latest-Linux-x86_64.sh’ saved [148981743/148981743]

PREFIX=/usr/local/miniconda
Unpacking payload ...

Installing base environment...

Preparing transaction: ...working... done
Executing transaction: ...working... done
installation finished.
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that you

In [ ]:
import sys
import os
sys.path.append('/usr/local/miniconda/bin')
os.environ['PATH'] = '/usr/local/miniconda/bin:' + os.environ['PATH']

In [ ]:
!conda --version

conda 24.7.1


In [ ]:
!conda create -y --name myenv python=3.8
!source activate myenv

Channels:
 - defaults
Platform: linux-64
Solving environment: - done

## Package Plan ##

  environment location: /usr/local/miniconda/envs/myenv

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-3.0.15             |       h5eee18b_0         5.2 MB
    pip-24.2                   |   py38h06a4308_0         2.2 MB
    python-3.8.19              |       h955ad1f_0        23.8 MB
    setuptools-72.1.0          |   py38h06a4308_0         2.4 MB
    wheel-0.43.0               |   py38h06a4308_0         109 KB
    ------------------------------------------------------------
                                           Total:        33.7 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main 
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu 
  ca-certificates    pkgs/mai

In [ ]:
!source deactivate

In [ ]:
!source activate myenv

/bin/bash: line 1: activate: No such file or directory


In [ ]:
!conda install -y numpy scipy pandas matplotlib scikit-learn

Channels:
 - defaults
Platform: linux-64
Solving environment: - \ | done

## Package Plan ##

  environment location: /usr/local/miniconda

  added / updated specs:
    - matplotlib
    - numpy
    - pandas
    - scikit-learn
    - scipy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.0                   |              mkl           6 KB
    bottleneck-1.3.7           |  py312ha883a20_0         140 KB
    brotli-1.0.9               |       h5eee18b_8          18 KB
    brotli-bin-1.0.9           |       h5eee18b_8          19 KB
    certifi-2024.8.30          |  py312h06a4308_0         163 KB
    contourpy-1.2.0            |  py312hdb19cb5_0         238 KB
    cycler-0.11.0              |     pyhd3eb1b0_0          12 KB
    cyrus-sasl-2.1.28          |       h52b45da_1         237 KB
    dbus-1.13.18               |       hb2f20db_0         504 KB
    fontconfig-2.14.1    

In [ ]:
import numpy as np
import scipy
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
print("Instalações bem-sucedidas!")

Instalações bem-sucedidas!


1. Crie um array unidimensional de 50 elementos contendo n´umeros inteiros
aleat´orios entre 10 e 100.
2. Gere uma matriz 4x4 com n´umeros inteiros de 1 a 16 e extraia a ´ultima
linha.
3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
`a 10ª posi¸c˜ao por 1.
4. Gere um array de 100 n´umeros inteiros aleat´orios e encontre a mediana e
a moda dos valores.
5. Crie um array de 20 elementos contendo n´umeros entre 1 e 100 e substitua
todos os valores m´ultiplos de 3 por -3.
6. Gere uma matriz 5x5 de n´umeros aleat´orios entre 0 e 1 e encontre a soma
de cada coluna.
7. Crie dois arrays de n´umeros aleat´orios e encontre a correla¸c˜ao entre eles.
8. Gere uma matriz 3x3 com n´umeros inteiros aleat´orios e eleve todos os seus
elementos ao quadrado.
9. Crie um array com 10 n´umeros aleat´orios e normalize seus valores entre 0
e 1.
10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores
crescentes de 1 a 6.
11. Gere um array de 100 n´umeros inteiros e encontre o valor que mais se
repete no array.
12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.
13. Crie um array contendo os 10 primeiros n´umeros pares e calcule sua soma
cumulativa.
14. Calcule a diferen¸ca entre dois arrays de n´umeros aleat´orios de mesmo
comprimento e encontre a m´edia das diferen¸cas.
15. Gere um array contendo 20 n´umeros e substitua todos os valores maiores
que 50 por 50.
16. Crie um array unidimensional e reorganize seus valores em uma matriz
3x4.
17. Gere uma matriz 4x4 de n´umeros inteiros aleat´orios e multiplique cada
valor por sua posi¸c˜ao na matriz.
2
18. Crie um array de 10 elementos contendo n´umeros entre 1 e 100 e substitua
todos os valores m´ultiplos de 5 por 0.
19. Crie dois arrays de n´umeros inteiros aleat´orios de tamanho 20 e calcule o
ˆangulo entre eles (produto escalar normalizado).
20. Crie uma matriz de n´umeros inteiros e encontre o valor m´ınimo de cada
linha

In [ ]:
array = np.random.randint(1,100, size=50)
print(array)

[64 52 44 14 13 10 79 50 13 79 90  7 87 95 81 26 13 75 72 40 68 82 77 70
  5 55 95 75 66 40 98 98 84 29 99 52 89 31 18 24 64 89 37  3 24 25 12 72
 12  1]


In [ ]:
array = np.array([[np.random.randint(1,16,size=16)]])
reshape = np.reshape(array,(4,4))
print(reshape)
print()
print(reshape[3:])

[[ 1 11  7  8]
 [ 1  3  4  2]
 [11  5 10  9]
 [11  9  8  5]]

[[11  9  8  5]]


In [ ]:
array = np.zeros(15)
print(array)
print()
array[4:10] = 1
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [ ]:
array = np.random.randint(1,10,size=100)
print(array)
print()

print(f"media: {np.median(array)}")

counts = {}
for i in array:
  counts.setdefault(i,0)
  counts[i] += 1


print()
moda = 0
maior = 0
for i,j in counts.items():
  if j > maior:
    maior = j
    moda = i


print(f"moda: {moda}")





[6 4 8 6 9 6 4 1 2 9 1 1 6 8 7 1 5 5 3 6 7 4 4 6 5 5 6 9 3 4 9 6 7 7 5 2 5
 9 8 3 2 4 9 4 6 9 1 3 1 9 2 4 3 9 9 5 4 7 6 9 4 6 4 1 2 7 6 2 3 5 6 7 4 9
 3 6 5 6 4 5 8 9 3 4 7 1 8 5 9 1 9 3 2 3 7 8 3 9 4 7]

media: 5.0

moda: 9


In [ ]:
array = np.random.randint(1,100,size=20)
print(array)

for i in range(0,len(array)):
  if array[i] % 3 == 0:
    array[i] = -3

print()
print(array)

[24 97 96 20 92 26  6  8 43 61 67 97 94 80 26 66 74 49  6 61]

[-3 97 -3 20 92 26 -3  8 43 61 67 97 94 80 26 -3 74 49 -3 61]


In [ ]:
array = np.random.rand(5,5)
print(array)
print()
transp = np.transpose(array)
for i in transp:
  print(i)
  print(f"soma: {np.sum(i)}")
  print()


[[0.04679155 0.5087468  0.29215791 0.15842955 0.74571506]
 [0.10362041 0.95806244 0.5638011  0.18761792 0.79248891]
 [0.08240697 0.50375969 0.11046507 0.94567358 0.51613267]
 [0.65083238 0.42215359 0.63521749 0.67760442 0.66625319]
 [0.00286622 0.09933532 0.06923683 0.62920752 0.58404604]]

[0.04679155 0.10362041 0.08240697 0.65083238 0.00286622]
soma: 0.8865175389359788

[0.5087468  0.95806244 0.50375969 0.42215359 0.09933532]
soma: 2.492057849787666

[0.29215791 0.5638011  0.11046507 0.63521749 0.06923683]
soma: 1.6708784056309636

[0.15842955 0.18761792 0.94567358 0.67760442 0.62920752]
soma: 2.5985329903745744

[0.74571506 0.79248891 0.51613267 0.66625319 0.58404604]
soma: 3.304635866499496



In [ ]:
array1 = np.random.randint(1,10,size=3)
array2 = np.random.randint(1,10,size=3)

print(array1)
print(array2)

np.corrcoef(array1,array2)

[1 8 2]
[6 3 5]


array([[ 1.        , -0.97986371],
       [-0.97986371,  1.        ]])

In [ ]:
array = np.random.randint(1,10,size=(3,3))
print(array)
print()
print(np.power(array,2))

[[3 6 5]
 [8 6 1]
 [9 3 1]]

[[ 9 36 25]
 [64 36  1]
 [81  9  1]]


In [ ]:
array = np.random.randint(1,10,size=10)
print(array)

array = (array-np.min(array))/(np.max(array)-np.min(array))

print(array)

[5 8 6 4 7 2 5 6 2 3]
[0.5        1.         0.66666667 0.33333333 0.83333333 0.
 0.5        0.66666667 0.         0.16666667]


In [ ]:
array = np.random.randint(1,10,size=10)
print(array)



[4 2 4 2 2 3 6 6 1 6]
[5 3 5 3 3 4 7 7 2 7]


In [ ]:
array = np.eye(6)
print(array)
x = 1
for i in range(0,len(array)):
  array[i][i] = x
  x += 1

print(array)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


In [ ]:
array = np.random.randint(1,10,size=100)
print(array)

counts = {}
for i in array:
  counts.setdefault(i,0)
  counts[i] += 1


print()
moda = 0
maior = 0
for i,j in counts.items():
  if j > maior:
    maior = j
    moda = i


print(f"moda: {moda}")



[3 6 3 5 2 4 8 4 2 7 9 1 8 8 9 2 2 7 5 8 1 6 9 1 4 7 6 5 8 8 8 2 7 2 9 5 1
 6 1 8 6 9 3 9 1 7 2 5 1 7 7 6 3 2 4 8 6 9 9 5 3 1 9 8 9 1 4 6 8 1 6 2 3 1
 7 6 1 9 3 1 3 7 9 6 4 4 8 6 8 2 4 2 3 8 9 9 3 4 2 8]

moda: 8


In [ ]:
array = np.eye(4)
print(array)

for i in range(0,len(array)):
  array[i][i] = 7


print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


In [ ]:
array = np.arange(0,21,2)
print(array)
print(np.sum(array))

[ 0  2  4  6  8 10 12 14 16 18 20]
110


In [ ]:
array1 = np.random.randint(1,10,size=3)
array2 = np.random.randint(1,10,size=3)

print(array1)
print(array2)
print()

aux = []
for i in range(0,3):
  if array1[i] > array2[i]:
    aux.append(array1[i]-array2[i])
  elif array2[i] > array1[i]:
    aux.append(array2[i]-array1[i])
  else:
    aux.append(0)

array3 = np.array(aux)
print(array3)
print(np.mean(array3))

[4 4 9]
[1 9 8]

[3 5 1]
3.0


In [ ]:
array = np.random.randint(1,100,size=20)
print(array)

for i in range (0,len(array)):
  if  array[i] > 50:
    array[i] = 50

print(array)

[63 17 41 55 13 50 93 59 90 13 87 24 37 86 68 33 92 54 51 12]
[50 17 41 50 13 50 50 50 50 13 50 24 37 50 50 33 50 50 50 12]


In [ ]:
array = np.arange(1,13)
print(array)
print()
array2 = np.reshape(array,(3,4))
print(array2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
array = np.random.randint(1,6,size=(4,4))
print(array)

count = 1
for item in array:
  for i in range(0,4):
    item[i] = item[i] * count
    count += 1
print()
print(array)



[[3 3 2 2]
 [4 4 3 5]
 [1 5 5 4]
 [5 1 3 1]]

[[ 3  6  6  8]
 [20 24 21 40]
 [ 9 50 55 48]
 [65 14 45 16]]


In [ ]:
array = np.random.randint(1,100,size=10)
print(array)

for i in range(0,len(array)):
  if array[i] % 5 == 0:
    array[i] = 0

print()
print(array)

[68 45 92 30 77 27 87 99 83 40]

[68  0 92  0 77 27 87 99 83  0]


In [ ]:
array1 = np.random.randint(1,10,size=20)
array2 = np.random.randint(1,10,size=20)

print(array)
print(array2)

print(np.dot(array1,array2))

[8 2 8 5 7 1 3 5 9 1 2 9 7 5 2 4 1 6 8 6]
[5 5 1 3 9 8 7 9 4 6 5 1 5 5 9 6 7 2 4 7]
496


In [ ]:
array = np.random.randint(1,10,size=(5,5))
print(array)

for item in array:
  print(item)
  print(f"menor numero: {np.min(item)}")

[[3 1 3 3 3]
 [6 1 3 7 3]
 [9 6 8 6 7]
 [8 4 7 4 2]
 [4 7 7 5 8]]
[3 1 3 3 3]
menor numero: 1
[6 1 3 7 3]
menor numero: 1
[9 6 8 6 7]
menor numero: 6
[8 4 7 4 2]
menor numero: 2
[4 7 7 5 8]
menor numero: 4
